project:
  type: website

website:  
  title: "mark michael"
  google-analytics: "G-XV04WJ9C9C"
  navbar:
    right:
      - about.qmd
      - text: "{{< iconify simple-icons bluesky >}}"
        href: https://bsky.app/profile/markmichael.dev
      - icon: linkedin
        href: https://linkedin.com/in/markmichael2
      - icon: github
        href: https://github.com/markmichael
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css



